### ISSUE TITLE
Client crash with acceleration/overclocked

### ISSUE THREAD

**Issue by LemADEC** [Lothrazar/RootsClassic#15]
As of 1.12.2-1.1.1, using an acceleration spell will cause a client crash, preventing anyone to load that area on the server:
```
java.lang.NullPointerException
    at net.minecraft.world.World.isOutsideBuildHeight(World.java:224)
    at net.minecraft.world.World.getTileEntity(World.java:2381)
    at elucent.rootsclassic.entity.EntityTileAccelerator.onUpdate(EntityTileAccelerator.java:35)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1990)
    at net.minecraft.world.World.updateEntity(World.java:1952)
    at net.minecraft.world.World.redirect$updateEntity$zbb000(World.java:4114)
    at net.minecraft.world.World.updateEntities(World.java:1756)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1846)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1097)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3940)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Also, there's no configuration option to disable the acceleration while this effect is frequently abused by players, causing major server CPU load.

**Comment by LemADEC** [comment]
From a quick code review, it appears both read and write are missing calls to their ancestor here:
https://github.com/PrinceOfAmber/RootsClassic/blob/master/src/main/java/elucent/rootsclassic/entity/EntityTileAccelerator.java#L76
