### ISSUE TITLE
Server internal error during casting (MP)

### ISSUE THREAD

**Issue by ZigTheHedge** [Lothrazar/RootsClassic#19]
Minecraft version & Mod Version:
Minecraft: 1.12.2, Roots: 1.1.1

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Trying to cast "Regeneration" with potency +1. Server kicks with "Internal server error".

Crash log (if any):
`net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayer.func_70016_h(DDD)V
        at elucent.rootsclassic.component.components.ComponentPeony.castingAction(ComponentPeony.java:52) ~[ComponentPeony.class:?]
        at elucent.rootsclassic.item.ItemStaff.onUsingTick(ItemStaff.java:169) ~[ItemStaff.class:?]
        at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2670) ~[vp.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2090) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
`

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/roots-classic/files/2659875
