### ISSUE TITLE
Fatal in Dedicated Server (latest 1.18 version of Roots)

### ISSUE THREAD

**Issue by itsdinkd** [Lothrazar/RootsClassic#62]
Forge 38.0.17
1.18
Latest Roots version

---

In latest.log you will find

```java
[19:39:33] [Thread-0/FATAL]: Roots Classic's config just got changed on the file system!
[19:39:33] [Thread-0/FATAL]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[19:39:33] [Thread-0/ERROR]: Exception caught during firing event: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$3728/0x00000008015e48a0@7a8df5aa
java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	at MC-BOOTSTRAP/fmlloader@1.18-38.0.17/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at TRANSFORMER/balm@2.3.0+0/net.blay09.mods.balm.forge.config.ForgeBalmConfig.lambda$initializeBackingConfig$3(ForgeBalmConfig.java:149)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at LAYER PLUGIN/javafmllanguage@1.18-38.0.17/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:55)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:149)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:149)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:90)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:160)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)

[19:39:33] [Thread-0/FATAL]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[19:39:33] [Thread-0/ERROR]: Exception caught during firing event: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$3728/0x00000008015e48a0@650523ed
java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	at MC-BOOTSTRAP/fmlloader@1.18-38.0.17/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at TRANSFORMER/balm@2.3.0+0/net.blay09.mods.balm.forge.config.ForgeBalmConfig.lambda$initializeBackingConfig$3(ForgeBalmConfig.java:149)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at LAYER PLUGIN/javafmllanguage@1.18-38.0.17/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:55)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:149)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:149)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:90)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:160)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)

[19:39:33] [Thread-0/FATAL]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[19:39:33] [Thread-0/ERROR]: Exception caught during firing event: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$3728/0x00000008015e48a0@177020a5
java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	at MC-BOOTSTRAP/fmlloader@1.18-38.0.17/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at TRANSFORMER/balm@2.3.0+0/net.blay09.mods.balm.forge.config.ForgeBalmConfig.lambda$initializeBackingConfig$3(ForgeBalmConfig.java:149)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at LAYER PLUGIN/javafmllanguage@1.18-38.0.17/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:55)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:149)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:149)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:90)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:160)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)```

**Comment by Mrbysco** [comment]
Have you tried without Balm?
